### ISSUE TITLE
Add functionality to make creepers respect spawn protection

### ISSUE THREAD

**Issue by itsdinkd** [Sindarin27/peeping-creepers#3]
Since adding Peeping Creepers for 1.17.1, and disabling their break blocks config, they have been bypassing spawn protecting and blowing up blocks while players choose a origin in spawn.

**Comment by Sindarin27** [comment]
Interestingly, this is vanilla behaviour! Mobs, tnt, pistons, etc are all allowed to bypass spawn protection. I'm not sure what to do about that, since adjusting such vanilla behaviours isn't the goal of this mod.

The difference my mod makes that makes this noticeable is probably the fact that the creepers spot you from farther away. Normally, most creepers wouldn't notice a player at spawn.

You could use a mod or data pack that gives players resistance for some time after they spawn. If that's not enough for you, please let me know and I'll put a spawn protection upgrade mod  on my idea list.

**Comment by itsdinkd** [comment]
no worries. I ended up just claiming spawn with Flan, however, I probably
would recommend if possible that spawn protection upgrade for other server
owners / modpack devs as you are right with the creepers not usually going
to spawn but with the range change it occurs frequently.

**Comment by itsdinkd** [comment]
Hi Sindarin, were you able to add that upgrade for spawn protection in the 1.18 release?

**Comment by Sindarin27** [comment]
Not yet, but I think this will be doable. I will take a look at it in due time.

**Comment by Sindarin27** [comment]
This is now included in the next 1.18 release, version 1.2 when it releases. The default setting keeps the current behaviour, but there will be a config setting `protectSpawn` to make creepers respect spawn protection. Creepers just barely outside the spawn protection range will still be able to blow up blocks inside the range, as will creepers that have already started blowing up and are then pushed inside the protection range.
